### ISSUE TITLE
Allow role to disable SSL verification

### ISSUE THREAD

**Issue by bachya** [ljurgs/unifi-config-gateway-json#1]
Is it possible to add a variable to disable SSL verification? I'm using UniFi's default self-hosted cert and when I attempt to use this role, I get:

```
fatal: [pmc-lxc-unifi.phil.lan]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)>", "redirected": false, "status": -1, "url": "https://172.16.10.10:8443/api/login"}
```

Presumably the role could tie a variable to the [`validate_certs`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html#parameter-validate_certs) option in `ansible.builtin.uri`?

**Comment by ljurgs** [comment]
I've merged your PR, thanks!

**Comment by bachya** [comment]
Thanks! Any ETA on a new release to Galaxy?

**Comment by ljurgs** [comment]
Done
